# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-03 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20200603_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='liked_image',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='liker',
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
