# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-31 08:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20200531_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
