# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-31 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20200531_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='anonymous.jpg', upload_to='profile/'),
        ),
    ]
